import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const svgDir = join(root, "node_modules", "octicons", "build", "svg");
const outFile = join(root, "src", "icons", "generated.ts");

const files = (await readdir(svgDir)).filter((f) => f.endsWith(".svg")).sort();

const entries = await Promise.all(
  files.map(async (file) => {
    const name = file.replace(/\.svg$/, "");
    const raw = (await readFile(join(svgDir, file), "utf8")).trim();
    return [name, raw];
  }),
);

const body = entries
  .map(([name, svg]) => `  ${JSON.stringify(name)}: ${JSON.stringify(svg)},`)
  .join("\n");

const out = `// generated by scripts/build-icons.mjs, do not edit
export const OCTICON_SVGS: Record<string, string> = {
${body}
};
`;

await mkdir(dirname(outFile), { recursive: true });
await writeFile(outFile, out, "utf8");

console.log(`wrote ${entries.length} icons → ${outFile}`);
